### PR TITLE
Added tlk777 tests

### PR DESCRIPTION
**Pull request by TylerKimbell**
Doing this super early so hopefully you get back to me before the end of the day.

### CODE REVIEW

**Comment by cindywu2018** [comment]
You accidentally submitted RunNetflix twice and called the second copy TestNetflix. Please fix. Thanks :)

**Comment by TylerKimbell** [comment]
Should be fixed.

**Comment by TylerKimbell** [comment]
Please get back to me. I really don't want the program to be 2 days late because my pull request wasn't accepted.

**Comment by cindywu2018** [comment]
Accepted.

**Comment by TylerKimbell** [comment]
Thank you so much

**Pull request merged**
