### PR TITLE
added cdb3499 tests

### PR DESCRIPTION
**Pull request by Chrisbaack**

### CODE REVIEW

**Comment by pscamman** [comment]
You must append your EID to the beginning of every file. Also, your TestCollatz.c++ file is empty.

**Comment by Chrisbaack** [comment]
I fixed it, did I need to close and redo the request or does it track the newest commit?

**Comment by pscamman** [comment]
You do not need to redo the request. The TestCollatz.out file is still empty, however.

**Comment by Chrisbaack** [comment]
Sorry.. I checked TestNetflix.c++ not TestNetflix.out. That's fixed now.

**Pull request merged**
